rm(list=ls())
setwd("C:\\Users\\Lenovo\\Desktop\\homework&slide\\data analytics")
EPI_data<-read.csv("2010EPI_data.csv",skip=1)
plot(ecdf(EPI_data$EPI),do.points=FALSE,verticals=TRUE)
plot(ecdf(EPI_data$EPI),do.points=TRUE,verticals=TRUE)
par(pty="s")
qqnorm(EPI_data$EPI)
qqline(EPI_data$EPI)
x<-seq(30,95)
x2<-seq(30,95,2)
windows()
qqplot(qt(ppoints(250),df=5),x,xlab="Q-Q plot")
qqline(x)
boxplot(EPI_data$EPI,EPI_data$DALY)

multivariate<-read.csv("multivariate.csv")
attach(multivariate)
mm<-lm(Homeowners~Immigrant)
print(mm)
summary(mm)
plot(Homeowners~Immigrant)
abline(mm)
abline(mm,col=2,lwd=3)
attributes(mm)
mm$coefficients

plot(mtcars$wt,mtcars$mpg)
library(ggplot2)
qplot(mtcars$wt,mtcars$mpg)
qplot(wt,mpg,data=mtcars)
ggplot(mtcars,aes(x=wt,y=mpg))+geom_point()
plot(pressure$temperature,pressure$pressure,type='l')
points(pressure$temperature,pressure$pressure)